# Basic stuff
title: Vijay Thakkar
description: >
  Mechanic @ HPC Garage. Grad student at Georgia Tech.
  I love big computers that run fast and I cannot lie.

# URLs
baseurl: ""
url: "https://www.thakkarv.dev"
permalink: /post/:title.html

# Version
css_version: 20200803


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM


# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md


# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
